// Compatibility facade. Consumers keep one stable import path while the
// implementation stays separated by responsibility below.
export {
  CARE_KEYS,
  EMPTY_FILTERS,
  FILTER_FACETS,
  GOOD_WITH_KEYS,
  GROUPS,
  TOGGLE_KEYS,
  TWO_TONED,
} from "./filters/contracts";
export type {
  AgeGroup,
  CoatColorFacet,
  WaitingGroup,
  CareKey,
  FilterFacet,
  FilterOption,
  Filters,
  GoodWithKey,
  MultiGroup,
  SpeciesFilter,
  ToggleKey,
} from "./filters/contracts";

export {
  FILTER_METADATA,
  TOGGLES,
  careOptions,
  type CareOption,
  goodWithOptions,
  groupLabel,
  groupOptions,
  optionLabel,
  toggleLabel,
  togglesAskedOf,
  valueChipLabel,
} from "./filters/metadata";
export type {
  FilterValueDefinition,
  ToggleDef,
} from "./filters/metadata";

export {
  activeFilterCount,
  waitingGroups,
  ageGroup,
  ageInMonths,
  ageStage,
  answeredByNone,
  applyFilters,
  bySpecies,
  careCounts,
  careMatches,
  chipGains,
  chipKey,
  facetCounts,
  namesUnanswered,
  picksEverySex,
  thinnestAnswer,
  unansweredBand,
  unansweredCounts,
  goodWithAnswer,
  goodWithCounts,
  goodWithMatches,
  isDrop,
  liveInPool,
  poolCounts,
  pruneHiddenFilters,
  speciesCounts,
  speciesFacetCounts,
  toggleCounts,
  toggleGroupValue,
  toggleValues,
  visibleCare,
  visibleGoodWith,
  visibleGroups,
  visibleToggles,
  type Coverage,
  type Question,
  type Unanswered,
  type UnansweredBand,
  type UnansweredTally,
} from "./filters/engine";

export {
  FILTER_PARAM_NAMES,
  OWNED_PARAM_NAMES,
  parseFilters,
  serializeFilters,
  shelterAnimalsPath,
} from "./filters/url";
