// GENERATED FILE. Do not edit by hand.
//
// Postcode -> municipality (občina), derived from the Register of Spatial
// Units published by the Surveying and Mapping Authority of the Republic of
// Slovenia (GURS), via github.com/stefanb/gurs-rpe (PT.geojson, OB.geojson).
// Licensed CC BY 4.0.
//
// A postal district may straddle municipalities. `municipalities` lists every
// one holding at least a twentieth of the district, largest share first, so a
// single entry is an answer and several entries are a question to put to the
// reader.
//
// Rebuild with: pnpm --filter web generate:postcode-municipalities

export type PostcodeMunicipality = {
  code: string;
  name: string;
  municipalities: string[];
};

export const POSTCODE_MUNICIPALITIES: PostcodeMunicipality[] = [
  { code: "1000", name: "Ljubljana", municipalities: ["Ljubljana"] },
  { code: "1210", name: "Ljubljana - Šentvid", municipalities: ["Ljubljana"] },
  { code: "1211", name: "Ljubljana - Šmartno", municipalities: ["Ljubljana", "Medvode", "Vodice"] },
  { code: "1215", name: "Medvode", municipalities: ["Medvode"] },
  { code: "1216", name: "Smlednik", municipalities: ["Medvode"] },
  { code: "1217", name: "Vodice", municipalities: ["Vodice"] },
  { code: "1218", name: "Komenda", municipalities: ["Komenda"] },
  { code: "1219", name: "Laze v Tuhinju", municipalities: ["Kamnik"] },
  { code: "1221", name: "Motnik", municipalities: ["Kamnik"] },
  { code: "1222", name: "Trojane", municipalities: ["Lukovica", "Vransko", "Zagorje ob Savi"] },
  { code: "1223", name: "Blagovica", municipalities: ["Lukovica", "Kamnik"] },
  { code: "1225", name: "Lukovica", municipalities: ["Lukovica"] },
  { code: "1230", name: "Domžale", municipalities: ["Domžale"] },
  { code: "1231", name: "Ljubljana - Črnuče", municipalities: ["Ljubljana"] },
  { code: "1233", name: "Dob", municipalities: ["Domžale"] },
  { code: "1234", name: "Mengeš", municipalities: ["Mengeš"] },
  { code: "1235", name: "Radomlje", municipalities: ["Domžale", "Kamnik"] },
  { code: "1236", name: "Trzin", municipalities: ["Trzin"] },
  { code: "1241", name: "Kamnik", municipalities: ["Kamnik"] },
  { code: "1242", name: "Stahovica", municipalities: ["Kamnik"] },
  { code: "1251", name: "Moravče", municipalities: ["Moravče"] },
  { code: "1252", name: "Vače", municipalities: ["Litija", "Zagorje ob Savi", "Moravče"] },
  { code: "1260", name: "Ljubljana - Polje", municipalities: ["Ljubljana"] },
  { code: "1261", name: "Ljubljana - Dobrunje", municipalities: ["Ljubljana"] },
  { code: "1262", name: "Dol pri Ljubljani", municipalities: ["Dol pri Ljubljani", "Moravče"] },
  { code: "1270", name: "Litija", municipalities: ["Litija"] },
  { code: "1272", name: "Polšnik", municipalities: ["Litija"] },
  { code: "1273", name: "Dole pri Litiji", municipalities: ["Litija"] },
  { code: "1274", name: "Gabrovka", municipalities: ["Litija"] },
  { code: "1275", name: "Šmartno pri Litiji", municipalities: ["Šmartno pri Litiji"] },
  { code: "1276", name: "Primskovo", municipalities: ["Šmartno pri Litiji"] },
  { code: "1281", name: "Kresnice", municipalities: ["Litija", "Moravče"] },
  { code: "1282", name: "Sava", municipalities: ["Litija", "Zagorje ob Savi"] },
  { code: "1290", name: "Grosuplje", municipalities: ["Grosuplje"] },
  { code: "1291", name: "Škofljica", municipalities: ["Škofljica"] },
  { code: "1292", name: "Ig", municipalities: ["Ig"] },
  { code: "1293", name: "Šmarje - Sap", municipalities: ["Grosuplje", "Ljubljana"] },
  { code: "1294", name: "Višnja Gora", municipalities: ["Ivančna Gorica"] },
  { code: "1295", name: "Ivančna Gorica", municipalities: ["Ivančna Gorica"] },
  { code: "1296", name: "Šentvid pri Stični", municipalities: ["Ivančna Gorica"] },
  { code: "1301", name: "Krka", municipalities: ["Ivančna Gorica", "Dobrepolje"] },
  { code: "1303", name: "Zagradec", municipalities: ["Ivančna Gorica", "Žužemberk"] },
  { code: "1310", name: "Ribnica", municipalities: ["Ribnica"] },
  { code: "1311", name: "Turjak", municipalities: ["Velike Lašče", "Grosuplje"] },
  { code: "1312", name: "Videm - Dobrepolje", municipalities: ["Dobrepolje", "Grosuplje"] },
  { code: "1313", name: "Struge", municipalities: ["Dobrepolje"] },
  { code: "1314", name: "Rob", municipalities: ["Velike Lašče"] },
  { code: "1315", name: "Velike Lašče", municipalities: ["Velike Lašče", "Ribnica"] },
  { code: "1316", name: "Ortnek", municipalities: ["Ribnica", "Sodražica"] },
  { code: "1317", name: "Sodražica", municipalities: ["Sodražica"] },
  { code: "1318", name: "Loški Potok", municipalities: ["Loški Potok", "Ribnica"] },
  { code: "1319", name: "Draga", municipalities: ["Loški Potok"] },
  { code: "1330", name: "Kočevje", municipalities: ["Kočevje"] },
  { code: "1331", name: "Dolenja vas", municipalities: ["Ribnica", "Loški Potok"] },
  { code: "1332", name: "Stara Cerkev", municipalities: ["Kočevje"] },
  { code: "1336", name: "Kostel", municipalities: ["Kostel"] },
  { code: "1337", name: "Osilnica", municipalities: ["Osilnica"] },
  { code: "1338", name: "Kočevska Reka", municipalities: ["Kočevje"] },
  { code: "1351", name: "Brezovica pri Ljubljani", municipalities: ["Brezovica", "Log - Dragomer"] },
  { code: "1352", name: "Preserje", municipalities: ["Brezovica"] },
  { code: "1353", name: "Borovnica", municipalities: ["Borovnica", "Vrhnika"] },
  { code: "1354", name: "Horjul", municipalities: ["Horjul", "Dobrova - Polhov Gradec", "Vrhnika"] },
  { code: "1355", name: "Polhov Gradec", municipalities: ["Dobrova - Polhov Gradec"] },
  { code: "1356", name: "Dobrova", municipalities: ["Dobrova - Polhov Gradec"] },
  { code: "1357", name: "Notranje Gorice", municipalities: ["Brezovica"] },
  { code: "1358", name: "Log pri Brezovici", municipalities: ["Vrhnika", "Log - Dragomer"] },
  { code: "1360", name: "Vrhnika", municipalities: ["Vrhnika"] },
  { code: "1370", name: "Logatec", municipalities: ["Logatec"] },
  { code: "1372", name: "Hotedršica", municipalities: ["Logatec"] },
  { code: "1373", name: "Rovte", municipalities: ["Logatec", "Idrija"] },
  { code: "1380", name: "Cerknica", municipalities: ["Cerknica"] },
  { code: "1381", name: "Rakek", municipalities: ["Cerknica"] },
  { code: "1382", name: "Begunje pri Cerknici", municipalities: ["Cerknica"] },
  { code: "1384", name: "Grahovo", municipalities: ["Cerknica"] },
  { code: "1385", name: "Nova Vas", municipalities: ["Bloke"] },
  { code: "1386", name: "Stari trg pri Ložu", municipalities: ["Loška dolina"] },
  { code: "1410", name: "Zagorje ob Savi", municipalities: ["Zagorje ob Savi"] },
  { code: "1411", name: "Izlake", municipalities: ["Zagorje ob Savi"] },
  { code: "1412", name: "Kisovec", municipalities: ["Zagorje ob Savi"] },
  { code: "1413", name: "Čemšenik", municipalities: ["Zagorje ob Savi"] },
  { code: "1414", name: "Podkum", municipalities: ["Zagorje ob Savi", "Litija"] },
  { code: "1420", name: "Trbovlje", municipalities: ["Trbovlje"] },
  { code: "1423", name: "Dobovec", municipalities: ["Trbovlje", "Radeče"] },
  { code: "1430", name: "Hrastnik", municipalities: ["Hrastnik"] },
  { code: "1431", name: "Dol pri Hrastniku", municipalities: ["Hrastnik"] },
  { code: "1432", name: "Zidani Most", municipalities: ["Laško"] },
  { code: "1433", name: "Radeče", municipalities: ["Radeče"] },
  { code: "1434", name: "Loka pri Zidanem Mostu", municipalities: ["Sevnica", "Laško"] },
  { code: "2000", name: "Maribor", municipalities: ["Maribor"] },
  { code: "2201", name: "Zgornja Kungota", municipalities: ["Kungota", "Maribor"] },
  { code: "2204", name: "Miklavž na Dravskem polju", municipalities: ["Miklavž na Dravskem polju", "Hoče - Slivnica"] },
  { code: "2205", name: "Starše", municipalities: ["Starše"] },
  { code: "2206", name: "Marjeta na Dravskem polju", municipalities: ["Starše"] },
  { code: "2208", name: "Pohorje", municipalities: ["Hoče - Slivnica", "Ruše", "Maribor", "Slovenska Bistrica"] },
  { code: "2211", name: "Pesnica pri Mariboru", municipalities: ["Pesnica", "Kungota"] },
  { code: "2212", name: "Šentilj v Slov. goricah", municipalities: ["Šentilj"] },
  { code: "2213", name: "Zgornja Velka", municipalities: ["Šentilj"] },
  { code: "2214", name: "Sladki Vrh", municipalities: ["Šentilj"] },
  { code: "2215", name: "Ceršak", municipalities: ["Šentilj"] },
  { code: "2221", name: "Jarenina", municipalities: ["Pesnica"] },
  { code: "2222", name: "Jakobski dol", municipalities: ["Pesnica", "Šentilj"] },
  { code: "2223", name: "Jurovski Dol", municipalities: ["Sveti Jurij v Slovenskih goricah"] },
  { code: "2229", name: "Malečnik", municipalities: ["Maribor"] },
  { code: "2230", name: "Lenart v Slov. goricah", municipalities: ["Lenart"] },
  { code: "2231", name: "Pernica", municipalities: ["Pesnica", "Maribor", "Lenart"] },
  { code: "2232", name: "Voličina", municipalities: ["Lenart"] },
  { code: "2233", name: "Sv. Ana v Slov. goricah", municipalities: ["Sveta Ana"] },
  { code: "2234", name: "Benedikt", municipalities: ["Benedikt"] },
  { code: "2235", name: "Sv. Trojica v Slov. goricah", municipalities: ["Sveta Trojica v Slovenskih goricah"] },
  { code: "2236", name: "Cerkvenjak", municipalities: ["Cerkvenjak"] },
  { code: "2241", name: "Spodnji Duplek", municipalities: ["Duplek", "Ptuj"] },
  { code: "2242", name: "Zgornja Korena", municipalities: ["Duplek"] },
  { code: "2250", name: "Ptuj", municipalities: ["Ptuj"] },
  { code: "2252", name: "Dornava", municipalities: ["Dornava", "Ptuj"] },
  { code: "2253", name: "Destrnik", municipalities: ["Destrnik"] },
  { code: "2254", name: "Trnovska vas", municipalities: ["Trnovska vas"] },
  { code: "2255", name: "Vitomarci", municipalities: ["Sveti Andraž v Slovenskih goricah"] },
  { code: "2256", name: "Juršinci", municipalities: ["Juršinci"] },
  { code: "2257", name: "Polenšak", municipalities: ["Dornava", "Juršinci"] },
  { code: "2258", name: "Sv.Tomaž", municipalities: ["Sveti Tomaž"] },
  { code: "2259", name: "Ivanjkovci", municipalities: ["Ormož", "Ljutomer"] },
  { code: "2270", name: "Ormož", municipalities: ["Ormož"] },
  { code: "2272", name: "Gorišnica", municipalities: ["Gorišnica"] },
  { code: "2273", name: "Podgorci", municipalities: ["Ormož"] },
  { code: "2274", name: "Velika Nedelja", municipalities: ["Ormož"] },
  { code: "2275", name: "Miklavž pri Ormožu", municipalities: ["Ormož"] },
  { code: "2276", name: "Kog", municipalities: ["Ormož"] },
  { code: "2277", name: "Središče ob Dravi", municipalities: ["Središče ob Dravi"] },
  { code: "2281", name: "Markovci", municipalities: ["Markovci"] },
  { code: "2282", name: "Cirkulane", municipalities: ["Cirkulane"] },
  { code: "2283", name: "Zavrč", municipalities: ["Zavrč"] },
  { code: "2284", name: "Videm pri Ptuju", municipalities: ["Videm"] },
  { code: "2285", name: "Zgornji Leskovec", municipalities: ["Videm", "Podlehnik"] },
  { code: "2286", name: "Podlehnik", municipalities: ["Podlehnik"] },
  { code: "2287", name: "Žetale", municipalities: ["Žetale"] },
  { code: "2288", name: "Hajdina", municipalities: ["Hajdina"] },
  { code: "2289", name: "Stoperce", municipalities: ["Majšperk", "Makole"] },
  { code: "2310", name: "Slovenska Bistrica", municipalities: ["Slovenska Bistrica"] },
  { code: "2311", name: "Hoče", municipalities: ["Hoče - Slivnica"] },
  { code: "2312", name: "Orehova vas", municipalities: ["Hoče - Slivnica"] },
  { code: "2313", name: "Fram", municipalities: ["Rače - Fram"] },
  { code: "2314", name: "Zgornja Polskava", municipalities: ["Slovenska Bistrica"] },
  { code: "2315", name: "Šmartno na Pohorju", municipalities: ["Slovenska Bistrica"] },
  { code: "2316", name: "Zgornja Ložnica", municipalities: ["Slovenska Bistrica"] },
  { code: "2317", name: "Oplotnica", municipalities: ["Slovenska Bistrica", "Oplotnica"] },
  { code: "2318", name: "Laporje", municipalities: ["Slovenska Bistrica"] },
  { code: "2319", name: "Poljčane", municipalities: ["Poljčane"] },
  { code: "2321", name: "Makole", municipalities: ["Makole", "Poljčane"] },
  { code: "2322", name: "Majšperk", municipalities: ["Majšperk"] },
  { code: "2323", name: "Ptujska Gora", municipalities: ["Majšperk", "Videm"] },
  { code: "2324", name: "Lovrenc na Dravskem polju", municipalities: ["Kidričevo", "Videm"] },
  { code: "2325", name: "Kidričevo", municipalities: ["Kidričevo"] },
  { code: "2326", name: "Cirkovce", municipalities: ["Kidričevo"] },
  { code: "2327", name: "Rače", municipalities: ["Rače - Fram", "Starše"] },
  { code: "2331", name: "Pragersko", municipalities: ["Slovenska Bistrica", "Kidričevo"] },
  { code: "2341", name: "Limbuš", municipalities: ["Maribor"] },
  { code: "2342", name: "Ruše", municipalities: ["Ruše"] },
  { code: "2343", name: "Fala", municipalities: ["Lovrenc na Pohorju", "Ruše"] },
  { code: "2344", name: "Lovrenc na Pohorju", municipalities: ["Lovrenc na Pohorju"] },
  { code: "2345", name: "Bistrica ob Dravi", municipalities: ["Ruše"] },
  { code: "2351", name: "Kamnica", municipalities: ["Maribor", "Kungota"] },
  { code: "2352", name: "Selnica ob Dravi", municipalities: ["Selnica ob Dravi"] },
  { code: "2353", name: "Sv. Duh na Ostrem Vrhu", municipalities: ["Selnica ob Dravi", "Podvelka"] },
  { code: "2354", name: "Bresternica", municipalities: ["Maribor"] },
  { code: "2360", name: "Radlje ob Dravi", municipalities: ["Radlje ob Dravi"] },
  { code: "2361", name: "Ožbalt", municipalities: ["Podvelka", "Selnica ob Dravi"] },
  { code: "2362", name: "Kapla", municipalities: ["Podvelka"] },
  { code: "2363", name: "Podvelka", municipalities: ["Podvelka", "Radlje ob Dravi"] },
  { code: "2364", name: "Ribnica na Pohorju", municipalities: ["Ribnica na Pohorju"] },
  { code: "2365", name: "Vuhred", municipalities: ["Radlje ob Dravi", "Vuzenica"] },
  { code: "2366", name: "Muta", municipalities: ["Muta", "Dravograd"] },
  { code: "2367", name: "Vuzenica", municipalities: ["Vuzenica", "Radlje ob Dravi"] },
  { code: "2370", name: "Dravograd", municipalities: ["Dravograd"] },
  { code: "2371", name: "Trbonje", municipalities: ["Dravograd"] },
  { code: "2372", name: "Libeliče", municipalities: ["Dravograd"] },
  { code: "2373", name: "Šentjanž pri Dravogradu", municipalities: ["Dravograd", "Slovenj Gradec"] },
  { code: "2380", name: "Slovenj Gradec", municipalities: ["Slovenj Gradec"] },
  { code: "2381", name: "Podgorje pri Slovenj Gradcu", municipalities: ["Slovenj Gradec"] },
  { code: "2382", name: "Mislinja", municipalities: ["Mislinja"] },
  { code: "2383", name: "Šmartno pri Slovenj Gradcu", municipalities: ["Slovenj Gradec"] },
  { code: "2390", name: "Ravne na Koroškem", municipalities: ["Ravne na Koroškem"] },
  { code: "2391", name: "Prevalje", municipalities: ["Prevalje", "Ravne na Koroškem"] },
  { code: "2392", name: "Mežica", municipalities: ["Mežica"] },
  { code: "2393", name: "Črna na Koroškem", municipalities: ["Črna na Koroškem"] },
  { code: "2394", name: "Kotlje", municipalities: ["Ravne na Koroškem"] },
  { code: "3000", name: "Celje", municipalities: ["Celje"] },
  { code: "3201", name: "Šmartno v Rožni dolini", municipalities: ["Celje"] },
  { code: "3202", name: "Ljubečna", municipalities: ["Celje"] },
  { code: "3203", name: "Nova Cerkev", municipalities: ["Vojnik"] },
  { code: "3204", name: "Dobrna", municipalities: ["Dobrna", "Žalec"] },
  { code: "3205", name: "Vitanje", municipalities: ["Vitanje"] },
  { code: "3206", name: "Stranice", municipalities: ["Zreče"] },
  { code: "3210", name: "Slovenske Konjice", municipalities: ["Slovenske Konjice"] },
  { code: "3211", name: "Škofja vas", municipalities: ["Celje", "Vojnik"] },
  { code: "3212", name: "Vojnik", municipalities: ["Vojnik"] },
  { code: "3213", name: "Frankolovo", municipalities: ["Vojnik", "Slovenske Konjice"] },
  { code: "3214", name: "Zreče", municipalities: ["Zreče"] },
  { code: "3215", name: "Loče", municipalities: ["Slovenske Konjice"] },
  { code: "3220", name: "Štore", municipalities: ["Štore"] },
  { code: "3221", name: "Teharje", municipalities: ["Celje"] },
  { code: "3222", name: "Dramlje", municipalities: ["Šentjur"] },
  { code: "3223", name: "Loka pri Žusmu", municipalities: ["Šentjur", "Šmarje pri Jelšah"] },
  { code: "3224", name: "Dobje pri Planini", municipalities: ["Dobje", "Šentjur"] },
  { code: "3225", name: "Planina pri Sevnici", municipalities: ["Šentjur", "Dobje"] },
  { code: "3230", name: "Šentjur", municipalities: ["Šentjur"] },
  { code: "3231", name: "Grobelno", municipalities: ["Šmarje pri Jelšah", "Šentjur"] },
  { code: "3232", name: "Ponikva", municipalities: ["Šentjur"] },
  { code: "3233", name: "Kalobje", municipalities: ["Šentjur"] },
  { code: "3240", name: "Šmarje pri Jelšah", municipalities: ["Šmarje pri Jelšah"] },
  { code: "3241", name: "Podplat", municipalities: ["Rogaška Slatina", "Šmarje pri Jelšah"] },
  { code: "3250", name: "Rogaška Slatina", municipalities: ["Rogaška Slatina"] },
  { code: "3252", name: "Rogatec", municipalities: ["Rogatec", "Rogaška Slatina"] },
  { code: "3253", name: "Pristava pri Mestinju", municipalities: ["Podčetrtek", "Šmarje pri Jelšah"] },
  { code: "3254", name: "Podčetrtek", municipalities: ["Podčetrtek"] },
  { code: "3255", name: "Buče", municipalities: ["Podčetrtek", "Kozje"] },
  { code: "3256", name: "Bistrica ob Sotli", municipalities: ["Bistrica ob Sotli"] },
  { code: "3257", name: "Podsreda", municipalities: ["Kozje", "Brežice"] },
  { code: "3260", name: "Kozje", municipalities: ["Kozje"] },
  { code: "3261", name: "Lesično", municipalities: ["Kozje"] },
  { code: "3262", name: "Prevorje", municipalities: ["Šentjur"] },
  { code: "3263", name: "Gorica pri Slivnici", municipalities: ["Šentjur", "Šmarje pri Jelšah"] },
  { code: "3264", name: "Sveti Štefan", municipalities: ["Šmarje pri Jelšah"] },
  { code: "3270", name: "Laško", municipalities: ["Laško"] },
  { code: "3271", name: "Šentrupert", municipalities: ["Laško"] },
  { code: "3272", name: "Rimske Toplice", municipalities: ["Laško"] },
  { code: "3273", name: "Jurklošter", municipalities: ["Laško"] },
  { code: "3301", name: "Petrovče", municipalities: ["Žalec"] },
  { code: "3302", name: "Griže", municipalities: ["Žalec"] },
  { code: "3303", name: "Gomilsko", municipalities: ["Braslovče"] },
  { code: "3304", name: "Tabor", municipalities: ["Tabor"] },
  { code: "3305", name: "Vransko", municipalities: ["Vransko"] },
  { code: "3310", name: "Žalec", municipalities: ["Žalec"] },
  { code: "3311", name: "Šempeter v Savinjski dolini", municipalities: ["Žalec"] },
  { code: "3312", name: "Prebold", municipalities: ["Prebold"] },
  { code: "3313", name: "Polzela", municipalities: ["Polzela"] },
  { code: "3314", name: "Braslovče", municipalities: ["Braslovče"] },
  { code: "3320", name: "Velenje", municipalities: ["Velenje"] },
  { code: "3325", name: "Šoštanj", municipalities: ["Šoštanj"] },
  { code: "3326", name: "Topolšica", municipalities: ["Šoštanj"] },
  { code: "3327", name: "Šmartno ob Paki", municipalities: ["Šmartno ob Paki", "Braslovče"] },
  { code: "3330", name: "Mozirje", municipalities: ["Mozirje"] },
  { code: "3331", name: "Nazarje", municipalities: ["Nazarje", "Mozirje"] },
  { code: "3332", name: "Rečica ob Savinji", municipalities: ["Rečica ob Savinji"] },
  { code: "3333", name: "Ljubno ob Savinji", municipalities: ["Ljubno"] },
  { code: "3334", name: "Luče", municipalities: ["Luče"] },
  { code: "3335", name: "Solčava", municipalities: ["Solčava"] },
  { code: "3341", name: "Šmartno ob Dreti", municipalities: ["Nazarje"] },
  { code: "3342", name: "Gornji Grad", municipalities: ["Gornji Grad"] },
  { code: "4000", name: "Kranj", municipalities: ["Kranj", "Šenčur"] },
  { code: "4201", name: "Zgornja Besnica", municipalities: ["Kranj"] },
  { code: "4202", name: "Naklo", municipalities: ["Naklo"] },
  { code: "4203", name: "Duplje", municipalities: ["Naklo"] },
  { code: "4204", name: "Golnik", municipalities: ["Kranj"] },
  { code: "4205", name: "Preddvor", municipalities: ["Preddvor", "Šenčur"] },
  { code: "4206", name: "Zgornje Jezersko", municipalities: ["Jezersko"] },
  { code: "4207", name: "Cerklje na Gorenjskem", municipalities: ["Cerklje na Gorenjskem"] },
  { code: "4208", name: "Šenčur", municipalities: ["Šenčur"] },
  { code: "4209", name: "Žabnica", municipalities: ["Kranj", "Škofja Loka"] },
  { code: "4210", name: "Brnik - Aerodrom", municipalities: ["Cerklje na Gorenjskem"] },
  { code: "4211", name: "Mavčiče", municipalities: ["Kranj"] },
  { code: "4212", name: "Visoko", municipalities: ["Šenčur"] },
  { code: "4220", name: "Škofja Loka", municipalities: ["Škofja Loka"] },
  { code: "4223", name: "Poljane nad Škofjo Loko", municipalities: ["Gorenja vas - Poljane"] },
  { code: "4224", name: "Gorenja vas", municipalities: ["Gorenja vas - Poljane"] },
  { code: "4225", name: "Sovodenj", municipalities: ["Gorenja vas - Poljane", "Žiri", "Cerkno"] },
  { code: "4226", name: "Žiri", municipalities: ["Žiri"] },
  { code: "4227", name: "Selca", municipalities: ["Škofja Loka", "Železniki"] },
  { code: "4228", name: "Železniki", municipalities: ["Železniki"] },
  { code: "4229", name: "Sorica", municipalities: ["Železniki"] },
  { code: "4240", name: "Radovljica", municipalities: ["Radovljica"] },
  { code: "4243", name: "Brezje", municipalities: ["Radovljica"] },
  { code: "4244", name: "Podnart", municipalities: ["Radovljica", "Tržič"] },
  { code: "4245", name: "Kropa", municipalities: ["Radovljica"] },
  { code: "4246", name: "Kamna Gorica", municipalities: ["Radovljica"] },
  { code: "4247", name: "Zgornje Gorje", municipalities: ["Gorje", "Bohinj"] },
  { code: "4248", name: "Lesce", municipalities: ["Radovljica", "Žirovnica"] },
  { code: "4260", name: "Bled", municipalities: ["Bled"] },
  { code: "4263", name: "Bohinjska Bela", municipalities: ["Bled"] },
  { code: "4264", name: "Bohinjska Bistrica", municipalities: ["Bohinj"] },
  { code: "4265", name: "Bohinjsko jezero", municipalities: ["Bohinj"] },
  { code: "4267", name: "Srednja vas v Bohinju", municipalities: ["Bohinj"] },
  { code: "4270", name: "Jesenice", municipalities: ["Jesenice"] },
  { code: "4273", name: "Blejska Dobrava", municipalities: ["Jesenice"] },
  { code: "4274", name: "Žirovnica", municipalities: ["Žirovnica", "Jesenice"] },
  { code: "4275", name: "Begunje na Gorenjskem", municipalities: ["Radovljica"] },
  { code: "4276", name: "Hrušica", municipalities: ["Jesenice"] },
  { code: "4280", name: "Kranjska Gora", municipalities: ["Kranjska Gora"] },
  { code: "4281", name: "Mojstrana", municipalities: ["Kranjska Gora"] },
  { code: "4282", name: "Gozd Martuljek", municipalities: ["Kranjska Gora"] },
  { code: "4283", name: "Rateče Planica", municipalities: ["Kranjska Gora"] },
  { code: "4290", name: "Tržič", municipalities: ["Tržič"] },
  { code: "4294", name: "Križe", municipalities: ["Tržič"] },
  { code: "5000", name: "Nova Gorica", municipalities: ["Nova Gorica"] },
  { code: "5210", name: "Deskle", municipalities: ["Kanal ob Soči"] },
  { code: "5211", name: "Kojsko", municipalities: ["Brda"] },
  { code: "5212", name: "Dobrovo v Brdih", municipalities: ["Brda"] },
  { code: "5213", name: "Kanal", municipalities: ["Kanal ob Soči"] },
  { code: "5214", name: "Kal nad Kanalom", municipalities: ["Kanal ob Soči"] },
  { code: "5215", name: "Ročinj", municipalities: ["Kanal ob Soči"] },
  { code: "5216", name: "Most na Soči", municipalities: ["Tolmin"] },
  { code: "5220", name: "Tolmin", municipalities: ["Tolmin"] },
  { code: "5222", name: "Kobarid", municipalities: ["Kobarid"] },
  { code: "5223", name: "Breginj", municipalities: ["Kobarid"] },
  { code: "5224", name: "Srpenica", municipalities: ["Bovec"] },
  { code: "5230", name: "Bovec", municipalities: ["Bovec"] },
  { code: "5231", name: "Log pod Mangartom", municipalities: ["Bovec"] },
  { code: "5232", name: "Soča", municipalities: ["Bovec"] },
  { code: "5242", name: "Grahovo ob Bači", municipalities: ["Tolmin"] },
  { code: "5243", name: "Podbrdo", municipalities: ["Tolmin", "Železniki"] },
  { code: "5250", name: "Solkan", municipalities: ["Nova Gorica"] },
  { code: "5251", name: "Grgar", municipalities: ["Nova Gorica"] },
  { code: "5252", name: "Trnovo pri Gorici", municipalities: ["Nova Gorica"] },
  { code: "5253", name: "Čepovan", municipalities: ["Nova Gorica"] },
  { code: "5261", name: "Šempas", municipalities: ["Nova Gorica"] },
  { code: "5262", name: "Črniče", municipalities: ["Ajdovščina"] },
  { code: "5263", name: "Dobravlje", municipalities: ["Ajdovščina"] },
  { code: "5270", name: "Ajdovščina", municipalities: ["Ajdovščina"] },
  { code: "5271", name: "Vipava", municipalities: ["Vipava", "Ajdovščina"] },
  { code: "5272", name: "Podnanos", municipalities: ["Vipava", "Divača"] },
  { code: "5273", name: "Col", municipalities: ["Ajdovščina"] },
  { code: "5274", name: "Črni Vrh nad Idrijo", municipalities: ["Idrija"] },
  { code: "5275", name: "Godovič", municipalities: ["Idrija", "Logatec"] },
  { code: "5280", name: "Idrija", municipalities: ["Idrija"] },
  { code: "5281", name: "Spodnja Idrija", municipalities: ["Idrija"] },
  { code: "5282", name: "Cerkno", municipalities: ["Cerkno", "Tolmin"] },
  { code: "5283", name: "Slap ob Idrijci", municipalities: ["Tolmin"] },
  { code: "5290", name: "Šempeter pri Gorici", municipalities: ["Šempeter - Vrtojba"] },
  { code: "5291", name: "Miren", municipalities: ["Miren - Kostanjevica"] },
  { code: "5292", name: "Renče", municipalities: ["Renče - Vogrsko", "Miren - Kostanjevica", "Nova Gorica"] },
  { code: "5293", name: "Volčja Draga", municipalities: ["Renče - Vogrsko"] },
  { code: "5294", name: "Dornberk", municipalities: ["Nova Gorica"] },
  { code: "5295", name: "Branik", municipalities: ["Nova Gorica", "Ajdovščina"] },
  { code: "5296", name: "Kostanjevica na Krasu", municipalities: ["Miren - Kostanjevica"] },
  { code: "5297", name: "Prvačina", municipalities: ["Nova Gorica"] },
  { code: "6000", name: "Koper - Capodistria", municipalities: ["Koper"] },
  { code: "6210", name: "Sežana", municipalities: ["Sežana"] },
  { code: "6215", name: "Divača", municipalities: ["Divača", "Sežana"] },
  { code: "6216", name: "Podgorje", municipalities: ["Koper"] },
  { code: "6217", name: "Vremski Britof", municipalities: ["Divača", "Pivka"] },
  { code: "6219", name: "Lokev", municipalities: ["Sežana"] },
  { code: "6221", name: "Dutovlje", municipalities: ["Sežana"] },
  { code: "6222", name: "Štanjel", municipalities: ["Komen", "Sežana", "Ajdovščina"] },
  { code: "6223", name: "Komen", municipalities: ["Komen"] },
  { code: "6224", name: "Senožeče", municipalities: ["Divača"] },
  { code: "6225", name: "Hruševje", municipalities: ["Postojna"] },
  { code: "6230", name: "Postojna", municipalities: ["Postojna"] },
  { code: "6232", name: "Planina", municipalities: ["Postojna"] },
  { code: "6240", name: "Kozina", municipalities: ["Hrpelje - Kozina"] },
  { code: "6242", name: "Materija", municipalities: ["Hrpelje - Kozina"] },
  { code: "6243", name: "Obrov", municipalities: ["Hrpelje - Kozina", "Ilirska Bistrica", "Divača"] },
  { code: "6244", name: "Podgrad", municipalities: ["Ilirska Bistrica"] },
  { code: "6250", name: "Ilirska Bistrica", municipalities: ["Ilirska Bistrica"] },
  { code: "6253", name: "Knežak", municipalities: ["Ilirska Bistrica"] },
  { code: "6254", name: "Jelšane", municipalities: ["Ilirska Bistrica"] },
  { code: "6255", name: "Prem", municipalities: ["Ilirska Bistrica", "Pivka"] },
  { code: "6256", name: "Košana", municipalities: ["Pivka"] },
  { code: "6257", name: "Pivka", municipalities: ["Pivka"] },
  { code: "6258", name: "Prestranek", municipalities: ["Postojna"] },
  { code: "6271", name: "Dekani", municipalities: ["Koper"] },
  { code: "6272", name: "Gračišče", municipalities: ["Koper"] },
  { code: "6273", name: "Marezige", municipalities: ["Koper"] },
  { code: "6274", name: "Šmarje", municipalities: ["Koper"] },
  { code: "6275", name: "Črni Kal", municipalities: ["Koper"] },
  { code: "6276", name: "Pobegi", municipalities: ["Koper"] },
  { code: "6280", name: "Ankaran - Ancarano", municipalities: ["Ankaran", "Koper"] },
  { code: "6281", name: "Škofije", municipalities: ["Koper"] },
  { code: "6310", name: "Izola - Isola", municipalities: ["Izola"] },
  { code: "6320", name: "Portorož - Portorose", municipalities: ["Piran"] },
  { code: "6330", name: "Piran - Pirano", municipalities: ["Piran"] },
  { code: "6333", name: "Sečovlje - Sicciole", municipalities: ["Piran"] },
  { code: "8000", name: "Novo mesto", municipalities: ["Novo mesto"] },
  { code: "8210", name: "Trebnje", municipalities: ["Trebnje"] },
  { code: "8211", name: "Dobrnič", municipalities: ["Trebnje"] },
  { code: "8212", name: "Velika Loka", municipalities: ["Trebnje"] },
  { code: "8213", name: "Veliki Gaber", municipalities: ["Trebnje"] },
  { code: "8216", name: "Mirna Peč", municipalities: ["Mirna Peč"] },
  { code: "8220", name: "Šmarješke Toplice", municipalities: ["Šmarješke Toplice"] },
  { code: "8222", name: "Otočec", municipalities: ["Novo mesto"] },
  { code: "8230", name: "Mokronog", municipalities: ["Mokronog - Trebelno"] },
  { code: "8231", name: "Trebelno", municipalities: ["Mokronog - Trebelno"] },
  { code: "8232", name: "Šentrupert", municipalities: ["Šentrupert"] },
  { code: "8233", name: "Mirna", municipalities: ["Mirna", "Šentrupert"] },
  { code: "8250", name: "Brežice", municipalities: ["Brežice"] },
  { code: "8253", name: "Artiče", municipalities: ["Brežice"] },
  { code: "8254", name: "Globoko", municipalities: ["Brežice"] },
  { code: "8255", name: "Pišece", municipalities: ["Brežice"] },
  { code: "8256", name: "Sromlje", municipalities: ["Brežice"] },
  { code: "8257", name: "Dobova", municipalities: ["Brežice"] },
  { code: "8258", name: "Kapele", municipalities: ["Brežice"] },
  { code: "8259", name: "Bizeljsko", municipalities: ["Brežice"] },
  { code: "8261", name: "Jesenice na Dolenjskem", municipalities: ["Brežice"] },
  { code: "8262", name: "Krška vas", municipalities: ["Brežice"] },
  { code: "8263", name: "Cerklje ob Krki", municipalities: ["Brežice"] },
  { code: "8270", name: "Krško", municipalities: ["Krško"] },
  { code: "8272", name: "Zdole", municipalities: ["Krško", "Brežice"] },
  { code: "8273", name: "Leskovec pri Krškem", municipalities: ["Krško"] },
  { code: "8274", name: "Raka", municipalities: ["Krško"] },
  { code: "8275", name: "Škocjan", municipalities: ["Škocjan"] },
  { code: "8276", name: "Bučka", municipalities: ["Škocjan"] },
  { code: "8280", name: "Brestanica", municipalities: ["Krško"] },
  { code: "8281", name: "Senovo", municipalities: ["Krško"] },
  { code: "8282", name: "Koprivnica", municipalities: ["Krško", "Kozje", "Brežice"] },
  { code: "8283", name: "Blanca", municipalities: ["Sevnica", "Krško"] },
  { code: "8290", name: "Sevnica", municipalities: ["Sevnica"] },
  { code: "8292", name: "Zabukovje", municipalities: ["Sevnica", "Krško"] },
  { code: "8293", name: "Studenec", municipalities: ["Sevnica"] },
  { code: "8294", name: "Boštanj", municipalities: ["Sevnica"] },
  { code: "8295", name: "Tržišče", municipalities: ["Sevnica", "Škocjan"] },
  { code: "8296", name: "Krmelj", municipalities: ["Sevnica", "Šentrupert"] },
  { code: "8297", name: "Šentjanž", municipalities: ["Sevnica"] },
  { code: "8310", name: "Šentjernej", municipalities: ["Šentjernej"] },
  { code: "8311", name: "Kostanjevica na Krki", municipalities: ["Kostanjevica na Krki"] },
  { code: "8312", name: "Podbočje", municipalities: ["Krško"] },
  { code: "8321", name: "Brusnice", municipalities: ["Novo mesto"] },
  { code: "8322", name: "Stopiče", municipalities: ["Novo mesto"] },
  { code: "8323", name: "Uršna sela", municipalities: ["Novo mesto", "Dolenjske Toplice"] },
  { code: "8330", name: "Metlika", municipalities: ["Metlika"] },
  { code: "8331", name: "Suhor", municipalities: ["Metlika"] },
  { code: "8332", name: "Gradac", municipalities: ["Metlika", "Črnomelj"] },
  { code: "8333", name: "Semič", municipalities: ["Semič"] },
  { code: "8340", name: "Črnomelj", municipalities: ["Črnomelj"] },
  { code: "8341", name: "Adlešiči", municipalities: ["Črnomelj"] },
  { code: "8342", name: "Stari trg ob Kolpi", municipalities: ["Črnomelj", "Kočevje"] },
  { code: "8343", name: "Dragatuš", municipalities: ["Črnomelj"] },
  { code: "8344", name: "Vinica", municipalities: ["Črnomelj"] },
  { code: "8350", name: "Dolenjske Toplice", municipalities: ["Dolenjske Toplice"] },
  { code: "8351", name: "Straža pri Novem mestu", municipalities: ["Straža", "Dolenjske Toplice"] },
  { code: "8360", name: "Žužemberk", municipalities: ["Žužemberk", "Trebnje"] },
  { code: "8361", name: "Dvor", municipalities: ["Žužemberk"] },
  { code: "8362", name: "Hinje", municipalities: ["Žužemberk"] },
  { code: "9000", name: "Murska Sobota", municipalities: ["Murska Sobota"] },
  { code: "9201", name: "Puconci", municipalities: ["Puconci"] },
  { code: "9202", name: "Mačkovci", municipalities: ["Puconci"] },
  { code: "9203", name: "Petrovci", municipalities: ["Gornji Petrovci", "Šalovci"] },
  { code: "9204", name: "Šalovci", municipalities: ["Šalovci", "Gornji Petrovci"] },
  { code: "9205", name: "Hodoš - Hodos", municipalities: ["Hodoš"] },
  { code: "9206", name: "Križevci", municipalities: ["Gornji Petrovci", "Šalovci", "Moravske Toplice"] },
  { code: "9207", name: "Prosenjakovci - Pártosfalva", municipalities: ["Moravske Toplice"] },
  { code: "9208", name: "Fokovci", municipalities: ["Moravske Toplice"] },
  { code: "9220", name: "Lendava - Lendva", municipalities: ["Lendava"] },
  { code: "9221", name: "Martjanci", municipalities: ["Moravske Toplice"] },
  { code: "9222", name: "Bogojina", municipalities: ["Moravske Toplice"] },
  { code: "9223", name: "Dobrovnik - Dobronak", municipalities: ["Dobrovnik", "Lendava"] },
  { code: "9224", name: "Turnišče", municipalities: ["Turnišče"] },
  { code: "9225", name: "Velika Polana", municipalities: ["Velika Polana"] },
  { code: "9226", name: "Moravske Toplice", municipalities: ["Moravske Toplice"] },
  { code: "9227", name: "Kobilje", municipalities: ["Kobilje"] },
  { code: "9231", name: "Beltinci", municipalities: ["Beltinci"] },
  { code: "9232", name: "Črenšovci", municipalities: ["Črenšovci"] },
  { code: "9233", name: "Odranci", municipalities: ["Odranci"] },
  { code: "9240", name: "Ljutomer", municipalities: ["Ljutomer"] },
  { code: "9241", name: "Veržej", municipalities: ["Veržej", "Ljutomer"] },
  { code: "9242", name: "Križevci pri Ljutomeru", municipalities: ["Križevci", "Ljutomer"] },
  { code: "9243", name: "Mala Nedelja", municipalities: ["Ljutomer"] },
  { code: "9244", name: "Sveti Jurij ob Ščavnici", municipalities: ["Sveti Jurij ob Ščavnici"] },
  { code: "9245", name: "Spodnji Ivanjci", municipalities: ["Gornja Radgona"] },
  { code: "9246", name: "Razkrižje", municipalities: ["Razkrižje"] },
  { code: "9250", name: "Gornja Radgona", municipalities: ["Gornja Radgona"] },
  { code: "9251", name: "Tišina", municipalities: ["Tišina"] },
  { code: "9252", name: "Radenci", municipalities: ["Radenci", "Gornja Radgona"] },
  { code: "9253", name: "Apače", municipalities: ["Apače"] },
  { code: "9261", name: "Cankova", municipalities: ["Cankova"] },
  { code: "9262", name: "Rogašovci", municipalities: ["Rogašovci"] },
  { code: "9263", name: "Kuzma", municipalities: ["Kuzma"] },
  { code: "9264", name: "Grad", municipalities: ["Grad"] },
  { code: "9265", name: "Bodonci", municipalities: ["Puconci"] },
];

/** One point per municipality, for measuring which shelters are nearest to a
 *  municipality we have no verified coverage for. */
export type MunicipalityCentroid = {
  name: string;
  lat: number;
  lon: number;
};

export const MUNICIPALITY_CENTROIDS: MunicipalityCentroid[] = [
  { name: "Ajdovščina", lat: 45.8993, lon: 13.9077 },
  { name: "Ankaran", lat: 45.5754, lon: 13.7424 },
  { name: "Apače", lat: 46.693, lon: 15.8735 },
  { name: "Beltinci", lat: 46.608, lon: 16.2317 },
  { name: "Benedikt", lat: 46.6173, lon: 15.891 },
  { name: "Bistrica ob Sotli", lat: 46.0587, lon: 15.647 },
  { name: "Bled", lat: 46.3456, lon: 14.0787 },
  { name: "Bloke", lat: 45.7839, lon: 14.5103 },
  { name: "Bohinj", lat: 46.2941, lon: 13.9159 },
  { name: "Borovnica", lat: 45.9132, lon: 14.3783 },
  { name: "Bovec", lat: 46.3556, lon: 13.6237 },
  { name: "Braslovče", lat: 46.2823, lon: 15.0256 },
  { name: "Brda", lat: 46.0125, lon: 13.5454 },
  { name: "Brezovica", lat: 45.9484, lon: 14.4245 },
  { name: "Brežice", lat: 45.9316, lon: 15.6211 },
  { name: "Cankova", lat: 46.7356, lon: 16.025 },
  { name: "Celje", lat: 46.2486, lon: 15.2661 },
  { name: "Cerklje na Gorenjskem", lat: 46.2528, lon: 14.5 },
  { name: "Cerknica", lat: 45.8048, lon: 14.378 },
  { name: "Cerkno", lat: 46.1247, lon: 13.9724 },
  { name: "Cerkvenjak", lat: 46.561, lon: 15.9425 },
  { name: "Cirkulane", lat: 46.3417, lon: 15.9954 },
  { name: "Črenšovci", lat: 46.5558, lon: 16.2958 },
  { name: "Črna na Koroškem", lat: 46.4634, lon: 14.8287 },
  { name: "Črnomelj", lat: 45.5208, lon: 15.1969 },
  { name: "Destrnik", lat: 46.4834, lon: 15.8805 },
  { name: "Divača", lat: 45.6862, lon: 14.0256 },
  { name: "Dobje", lat: 46.1325, lon: 15.3971 },
  { name: "Dobrepolje", lat: 45.822, lon: 14.7357 },
  { name: "Dobrna", lat: 46.3563, lon: 15.2236 },
  { name: "Dobrova - Polhov Gradec", lat: 46.0617, lon: 14.3113 },
  { name: "Dobrovnik", lat: 46.651, lon: 16.3469 },
  { name: "Dol pri Ljubljani", lat: 46.094, lon: 14.673 },
  { name: "Dolenjske Toplice", lat: 45.7244, lon: 15.033 },
  { name: "Domžale", lat: 46.1451, lon: 14.627 },
  { name: "Dornava", lat: 46.4489, lon: 15.9904 },
  { name: "Dravograd", lat: 46.5975, lon: 15.0339 },
  { name: "Duplek", lat: 46.5117, lon: 15.7664 },
  { name: "Gorenja vas - Poljane", lat: 46.1148, lon: 14.1359 },
  { name: "Gorišnica", lat: 46.406, lon: 16.0107 },
  { name: "Gorje", lat: 46.3903, lon: 13.9827 },
  { name: "Gornja Radgona", lat: 46.6361, lon: 15.9615 },
  { name: "Gornji Grad", lat: 46.2881, lon: 14.7883 },
  { name: "Gornji Petrovci", lat: 46.8073, lon: 16.2051 },
  { name: "Grad", lat: 46.7944, lon: 16.0949 },
  { name: "Grosuplje", lat: 45.9395, lon: 14.6694 },
  { name: "Hajdina", lat: 46.4202, lon: 15.8258 },
  { name: "Hoče - Slivnica", lat: 46.4911, lon: 15.6271 },
  { name: "Hodoš", lat: 46.8281, lon: 16.3207 },
  { name: "Horjul", lat: 46.0225, lon: 14.2867 },
  { name: "Hrastnik", lat: 46.1313, lon: 15.1187 },
  { name: "Hrpelje - Kozina", lat: 45.5695, lon: 14.0087 },
  { name: "Idrija", lat: 45.9891, lon: 14.0045 },
  { name: "Ig", lat: 45.9332, lon: 14.5163 },
  { name: "Ilirska Bistrica", lat: 45.5664, lon: 14.2863 },
  { name: "Ivančna Gorica", lat: 45.9163, lon: 14.8122 },
  { name: "Izola", lat: 45.5134, lon: 13.6585 },
  { name: "Jesenice", lat: 46.4492, lon: 14.0721 },
  { name: "Jezersko", lat: 46.387, lon: 14.4829 },
  { name: "Juršinci", lat: 46.4856, lon: 15.973 },
  { name: "Kamnik", lat: 46.2571, lon: 14.677 },
  { name: "Kanal ob Soči", lat: 46.0837, lon: 13.6523 },
  { name: "Kidričevo", lat: 46.3951, lon: 15.7498 },
  { name: "Kobarid", lat: 46.2516, lon: 13.5554 },
  { name: "Kobilje", lat: 46.6809, lon: 16.391 },
  { name: "Kočevje", lat: 45.6183, lon: 14.903 },
  { name: "Komen", lat: 45.815, lon: 13.7543 },
  { name: "Komenda", lat: 46.203, lon: 14.5415 },
  { name: "Koper", lat: 45.5097, lon: 13.8381 },
  { name: "Kostanjevica na Krki", lat: 45.8376, lon: 15.4207 },
  { name: "Kostel", lat: 45.4989, lon: 14.8621 },
  { name: "Kozje", lat: 46.0719, lon: 15.5495 },
  { name: "Kranj", lat: 46.255, lon: 14.3341 },
  { name: "Kranjska Gora", lat: 46.4605, lon: 13.8461 },
  { name: "Križevci", lat: 46.564, lon: 16.118 },
  { name: "Krško", lat: 45.9559, lon: 15.463 },
  { name: "Kungota", lat: 46.6454, lon: 15.6012 },
  { name: "Kuzma", lat: 46.8405, lon: 16.0948 },
  { name: "Laško", lat: 46.1327, lon: 15.2579 },
  { name: "Lenart", lat: 46.5578, lon: 15.8187 },
  { name: "Lendava", lat: 46.5557, lon: 16.4463 },
  { name: "Litija", lat: 46.0563, lon: 14.9196 },
  { name: "Ljubljana", lat: 46.0543, lon: 14.5629 },
  { name: "Ljubno", lat: 46.3704, lon: 14.844 },
  { name: "Ljutomer", lat: 46.5211, lon: 16.157 },
  { name: "Log - Dragomer", lat: 46.0144, lon: 14.3733 },
  { name: "Logatec", lat: 45.9288, lon: 14.1928 },
  { name: "Loška dolina", lat: 45.6684, lon: 14.4836 },
  { name: "Loški Potok", lat: 45.6637, lon: 14.6408 },
  { name: "Lovrenc na Pohorju", lat: 46.5259, lon: 15.3836 },
  { name: "Luče", lat: 46.3557, lon: 14.7274 },
  { name: "Lukovica", lat: 46.1796, lon: 14.7675 },
  { name: "Majšperk", lat: 46.3244, lon: 15.7395 },
  { name: "Makole", lat: 46.3158, lon: 15.6749 },
  { name: "Maribor", lat: 46.5635, lon: 15.6273 },
  { name: "Markovci", lat: 46.3906, lon: 15.9488 },
  { name: "Medvode", lat: 46.131, lon: 14.4004 },
  { name: "Mengeš", lat: 46.1596, lon: 14.5576 },
  { name: "Metlika", lat: 45.656, lon: 15.2969 },
  { name: "Mežica", lat: 46.5187, lon: 14.8575 },
  { name: "Miklavž na Dravskem polju", lat: 46.4887, lon: 15.7072 },
  { name: "Miren - Kostanjevica", lat: 45.8522, lon: 13.6381 },
  { name: "Mirna", lat: 45.9452, lon: 15.057 },
  { name: "Mirna Peč", lat: 45.8546, lon: 15.0821 },
  { name: "Mislinja", lat: 46.447, lon: 15.2199 },
  { name: "Mokronog - Trebelno", lat: 45.9152, lon: 15.1575 },
  { name: "Moravče", lat: 46.1345, lon: 14.7576 },
  { name: "Moravske Toplice", lat: 46.7093, lon: 16.2702 },
  { name: "Mozirje", lat: 46.3605, lon: 14.9554 },
  { name: "Murska Sobota", lat: 46.6484, lon: 16.1548 },
  { name: "Muta", lat: 46.6275, lon: 15.1349 },
  { name: "Naklo", lat: 46.2917, lon: 14.2964 },
  { name: "Nazarje", lat: 46.2827, lon: 14.913 },
  { name: "Nova Gorica", lat: 45.9805, lon: 13.7406 },
  { name: "Novo mesto", lat: 45.7808, lon: 15.1938 },
  { name: "Odranci", lat: 46.586, lon: 16.2713 },
  { name: "Oplotnica", lat: 46.3857, lon: 15.4489 },
  { name: "Ormož", lat: 46.4376, lon: 16.1515 },
  { name: "Osilnica", lat: 45.5471, lon: 14.732 },
  { name: "Pesnica", lat: 46.6196, lon: 15.7099 },
  { name: "Piran", lat: 45.4872, lon: 13.634 },
  { name: "Pivka", lat: 45.6817, lon: 14.2357 },
  { name: "Podčetrtek", lat: 46.1433, lon: 15.5859 },
  { name: "Podlehnik", lat: 46.3162, lon: 15.8653 },
  { name: "Podvelka", lat: 46.595, lon: 15.3593 },
  { name: "Poljčane", lat: 46.3051, lon: 15.595 },
  { name: "Polzela", lat: 46.303, lon: 15.0851 },
  { name: "Postojna", lat: 45.7895, lon: 14.1699 },
  { name: "Prebold", lat: 46.2178, lon: 15.0897 },
  { name: "Preddvor", lat: 46.3242, lon: 14.4649 },
  { name: "Prevalje", lat: 46.5524, lon: 14.8949 },
  { name: "Ptuj", lat: 46.4419, lon: 15.8742 },
  { name: "Puconci", lat: 46.7445, lon: 16.1338 },
  { name: "Rače - Fram", lat: 46.4488, lon: 15.6456 },
  { name: "Radeče", lat: 46.0598, lon: 15.1442 },
  { name: "Radenci", lat: 46.62, lon: 16.0442 },
  { name: "Radlje ob Dravi", lat: 46.6037, lon: 15.2436 },
  { name: "Radovljica", lat: 46.3379, lon: 14.2024 },
  { name: "Ravne na Koroškem", lat: 46.5458, lon: 14.9611 },
  { name: "Razkrižje", lat: 46.5205, lon: 16.2741 },
  { name: "Rečica ob Savinji", lat: 46.3281, lon: 14.9031 },
  { name: "Renče - Vogrsko", lat: 45.8911, lon: 13.6799 },
  { name: "Ribnica", lat: 45.7327, lon: 14.718 },
  { name: "Ribnica na Pohorju", lat: 46.524, lon: 15.2601 },
  { name: "Rogaška Slatina", lat: 46.2478, lon: 15.6285 },
  { name: "Rogašovci", lat: 46.7996, lon: 16.026 },
  { name: "Rogatec", lat: 46.2386, lon: 15.7421 },
  { name: "Ruše", lat: 46.5166, lon: 15.4871 },
  { name: "Selnica ob Dravi", lat: 46.5863, lon: 15.4833 },
  { name: "Semič", lat: 45.6517, lon: 15.1443 },
  { name: "Sevnica", lat: 46.0102, lon: 15.2689 },
  { name: "Sežana", lat: 45.7362, lon: 13.8816 },
  { name: "Slovenj Gradec", lat: 46.4894, lon: 15.0787 },
  { name: "Slovenska Bistrica", lat: 46.414, lon: 15.5337 },
  { name: "Slovenske Konjice", lat: 46.3227, lon: 15.4612 },
  { name: "Sodražica", lat: 45.7575, lon: 14.6179 },
  { name: "Solčava", lat: 46.405, lon: 14.6581 },
  { name: "Središče ob Dravi", lat: 46.4026, lon: 16.2551 },
  { name: "Starše", lat: 46.4579, lon: 15.7554 },
  { name: "Straža", lat: 45.7772, lon: 15.0913 },
  { name: "Sveta Ana", lat: 46.6524, lon: 15.8362 },
  { name: "Sveta Trojica v Slovenskih goricah", lat: 46.5698, lon: 15.8862 },
  { name: "Sveti Andraž v Slovenskih goricah", lat: 46.523, lon: 15.9523 },
  { name: "Sveti Jurij ob Ščavnici", lat: 46.5648, lon: 16.0245 },
  { name: "Sveti Jurij v Slovenskih goricah", lat: 46.6128, lon: 15.7882 },
  { name: "Sveti Tomaž", lat: 46.4797, lon: 16.0668 },
  { name: "Šalovci", lat: 46.8333, lon: 16.2618 },
  { name: "Šempeter - Vrtojba", lat: 45.9154, lon: 13.6468 },
  { name: "Šenčur", lat: 46.2352, lon: 14.4261 },
  { name: "Šentilj", lat: 46.6758, lon: 15.716 },
  { name: "Šentjernej", lat: 45.8265, lon: 15.3325 },
  { name: "Šentjur", lat: 46.1897, lon: 15.4242 },
  { name: "Šentrupert", lat: 45.9843, lon: 15.0896 },
  { name: "Škocjan", lat: 45.9167, lon: 15.2983 },
  { name: "Škofja Loka", lat: 46.1612, lon: 14.2762 },
  { name: "Škofljica", lat: 45.9658, lon: 14.5736 },
  { name: "Šmarje pri Jelšah", lat: 46.2149, lon: 15.5199 },
  { name: "Šmarješke Toplice", lat: 45.8841, lon: 15.2435 },
  { name: "Šmartno ob Paki", lat: 46.3403, lon: 15.0306 },
  { name: "Šmartno pri Litiji", lat: 46.0228, lon: 14.8448 },
  { name: "Šoštanj", lat: 46.4061, lon: 15.0049 },
  { name: "Štore", lat: 46.1985, lon: 15.3228 },
  { name: "Tabor", lat: 46.2206, lon: 15.0092 },
  { name: "Tišina", lat: 46.661, lon: 16.0785 },
  { name: "Tolmin", lat: 46.1699, lon: 13.8088 },
  { name: "Trbovlje", lat: 46.1413, lon: 15.0499 },
  { name: "Trebnje", lat: 45.906, lon: 14.9739 },
  { name: "Trnovska vas", lat: 46.5228, lon: 15.8885 },
  { name: "Trzin", lat: 46.1279, lon: 14.5523 },
  { name: "Tržič", lat: 46.3885, lon: 14.3308 },
  { name: "Turnišče", lat: 46.6161, lon: 16.3135 },
  { name: "Velenje", lat: 46.369, lon: 15.1327 },
  { name: "Velika Polana", lat: 46.5788, lon: 16.3536 },
  { name: "Velike Lašče", lat: 45.8431, lon: 14.5871 },
  { name: "Veržej", lat: 46.5826, lon: 16.1641 },
  { name: "Videm", lat: 46.347, lon: 15.8929 },
  { name: "Vipava", lat: 45.8219, lon: 13.9849 },
  { name: "Vitanje", lat: 46.4023, lon: 15.2935 },
  { name: "Vodice", lat: 46.1712, lon: 14.4931 },
  { name: "Vojnik", lat: 46.3184, lon: 15.3083 },
  { name: "Vransko", lat: 46.2364, lon: 14.9445 },
  { name: "Vrhnika", lat: 45.9592, lon: 14.2948 },
  { name: "Vuzenica", lat: 46.5684, lon: 15.1599 },
  { name: "Zagorje ob Savi", lat: 46.1338, lon: 14.9516 },
  { name: "Zavrč", lat: 46.3615, lon: 16.0461 },
  { name: "Zreče", lat: 46.4001, lon: 15.3664 },
  { name: "Žalec", lat: 46.2591, lon: 15.1657 },
  { name: "Železniki", lat: 46.2187, lon: 14.1103 },
  { name: "Žetale", lat: 46.2825, lon: 15.8008 },
  { name: "Žiri", lat: 46.0464, lon: 14.1154 },
  { name: "Žirovnica", lat: 46.4107, lon: 14.1688 },
  { name: "Žužemberk", lat: 45.808, lon: 14.9311 },
];
