# Generated by Django 5.2.17 on 2026-08-18 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnimalOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("animal_id", models.CharField(max_length=200)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "available"),
                            ("reserved", "reserved"),
                            ("adopted", "adopted"),
                            ("hold", "hold"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "male"),
                            ("female", "female"),
                            ("unknown", "unknown"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=200, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "approximate_age_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("small", "small"),
                            ("medium", "medium"),
                            ("large", "large"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animal_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_overrides",
                        to="core.shelter",
                    ),
                ),
            ],
            options={
                "ordering": ["shelter__slug", "animal_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shelter", "animal_id"),
                        name="unique_shelter_animal_override",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShelterMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.shelter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelter_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["shelter__name", "user__email"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "shelter"),
                        name="unique_user_shelter_membership",
                    )
                ],
            },
        ),
    ]
