# Generated by Django 5.2.17 on 2026-08-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animaloverride",
            name="good_with_cats",
            field=models.CharField(
                blank=True,
                choices=[("yes", "yes"), ("no", "no"), ("unknown", "unknown")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="animaloverride",
            name="good_with_dogs",
            field=models.CharField(
                blank=True,
                choices=[("yes", "yes"), ("no", "no"), ("unknown", "unknown")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="animaloverride",
            name="good_with_kids",
            field=models.CharField(
                blank=True,
                choices=[("yes", "yes"), ("no", "no"), ("unknown", "unknown")],
                max_length=16,
                null=True,
            ),
        ),
    ]
