# Generated by Django 5.2.17 on 2026-08-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_animaloverride_good_with_cats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animaloverride",
            name="energy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("calm", "calm"),
                    ("balanced", "balanced"),
                    ("lively", "lively"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
