# Generated by Django 5.2.17 on 2026-08-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_animaloverride_energy"),
    ]

    operations = [
        migrations.AddField(
            model_name="animaloverride",
            name="baseline",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="animaloverride",
            name="baseline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
