# Generated by Django 5.2.17 on 2026-08-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_animaloverride_baseline_animaloverride_baseline_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="animaloverride",
            name="apartment_ok",
            field=models.CharField(
                blank=True,
                choices=[("yes", "yes"), ("no", "no"), ("unknown", "unknown")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="animaloverride",
            name="special_needs",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
