# Generated by Django 5.2.17 on 2026-09-01 21:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_animaloverride_apartment_ok_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shelter",
            name="ingestion",
            field=models.CharField(
                choices=[
                    ("scrape", "scrape"),
                    ("api", "api"),
                    ("rss", "rss"),
                    ("manual", "manual"),
                ],
                default="scrape",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("dog", "dog"),
                            ("cat", "cat"),
                            ("rabbit", "rabbit"),
                            ("other", "other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "available"),
                            ("reserved", "reserved"),
                            ("adopted", "adopted"),
                            ("hold", "hold"),
                        ],
                        default="available",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "male"),
                            ("female", "female"),
                            ("unknown", "unknown"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=200, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "approximate_age_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("small", "small"),
                            ("medium", "medium"),
                            ("large", "large"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "energy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("calm", "calm"),
                            ("balanced", "balanced"),
                            ("lively", "lively"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "good_with_kids",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "yes"), ("no", "no"), ("unknown", "unknown")],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "good_with_dogs",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "yes"), ("no", "no"), ("unknown", "unknown")],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "good_with_cats",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "yes"), ("no", "no"), ("unknown", "unknown")],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "apartment_ok",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "yes"), ("no", "no"), ("unknown", "unknown")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("special_needs", models.BooleanField(blank=True, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="core.shelter",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ListingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to=core.models.listing_photo_path)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("position", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("listing", "position"),
                        name="unique_listing_photo_position",
                    )
                ],
            },
        ),
    ]
