# Generated by Django 6.1.1 on 2026-10-07 18:21

from django.db import migrations, models

import core.profile_validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_drop_empty_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="animaloverride",
            name="adoption_requirements",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[core.profile_validators.validate_requirements],
            ),
        ),
        migrations.AddField(
            model_name="animaloverride",
            name="coat_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black", "black"),
                    ("white", "white"),
                    ("grey", "grey"),
                    ("brown", "brown"),
                    ("orange", "orange"),
                    ("cream", "cream"),
                    ("black-white", "black-white"),
                    ("brown-white", "brown-white"),
                    ("grey-white", "grey-white"),
                    ("orange-white", "orange-white"),
                    ("cream-white", "cream-white"),
                    ("multicolour", "multicolour"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="animaloverride",
            name="coat_colors",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[core.profile_validators.validate_coat_colors],
            ),
        ),
        migrations.AddField(
            model_name="animaloverride",
            name="coat_length",
            field=models.CharField(
                blank=True,
                choices=[
                    ("short", "short"),
                    ("medium", "medium"),
                    ("long", "long"),
                    ("hairless", "hairless"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="animaloverride",
            name="found_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animaloverride",
            name="intake_by",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animaloverride",
            name="intake_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animaloverride",
            name="life_stage",
            field=models.CharField(
                blank=True,
                choices=[("young", "young"), ("adult", "adult"), ("senior", "senior")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="animaloverride",
            name="medical",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[core.profile_validators.validate_medical],
            ),
        ),
        migrations.AddField(
            model_name="animaloverride",
            name="species",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dog", "dog"),
                    ("cat", "cat"),
                    ("rabbit", "rabbit"),
                    ("other", "other"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
