// Generated by scripts/generate-operation-types.mjs. Do not edit.
export declare const ARTIFACT_LOCK_VERSION = 1;
export type ProcessProbe = import('./operation-types.js').ProcessProbe;
export type ArtifactLockOwner = import('./operation-types.js').ArtifactLockOwner;
export type ArtifactLockRuntime = import('./operation-types.js').ArtifactLockRuntime;
export type AcquireArtifactLockOptions = import('./operation-types.js').AcquireArtifactLockOptions;
/** A stable machine identity; null disables automatic cross-run recovery. */
export declare function machineIdentity(): string | null;
/**
 * Identify the lock without resolving the lock itself. Resolving only its
 * existing parent makes a copied lock name the checkout where it was made,
 * while still treating two spellings of a symlinked parent as one checkout.
 */
/** @param {string} lockDir */
export declare function artifactLockIdentity(lockDir: string): string;
/** @param {number} pid @returns {ProcessProbe} */
export declare function probeProcess(pid: number): ProcessProbe;
/**
 * Acquire the checkout-wide generated-artifact lock.
 * @param {AcquireArtifactLockOptions} options
 * @returns {{token: string, owner: ArtifactLockOwner}}
 */
export declare function acquireArtifactLock({ activity, lockDir, holderPid, runtime: runtimeOverrides, }: AcquireArtifactLockOptions): {
    token: string;
    owner: ArtifactLockOwner;
};
/**
 * Release only the exact lock returned by acquireArtifactLock.
 * @param {{lockDir: string, token: string}} options
 */
export declare function releaseArtifactLock({ lockDir, token }: {
    lockDir: string;
    token: string;
}): void;
