// Generated by scripts/generate-operation-types.mjs. Do not edit.
export type GenerationReceipt = import('./operation-types.js').GenerationReceipt;
export type GenerationReceiptPaths = import('./operation-types.js').GenerationReceiptPaths;
export type GenerationReceiptValidation = import('./operation-types.js').GenerationReceiptValidation;
export type GenerationRepair = import('./operation-types.js').GenerationRepair;
/** @typedef {import('./operation-types.js').GenerationReceipt} GenerationReceipt */
/** @typedef {import('./operation-types.js').GenerationReceiptPaths} GenerationReceiptPaths */
/** @typedef {import('./operation-types.js').GenerationReceiptValidation} GenerationReceiptValidation */
/** @typedef {import('./operation-types.js').GenerationRepair} GenerationRepair */
export declare const GENERATION_RECEIPT_VERSION = 1;
export declare const GENERATION_RECEIPT_FILE = "generation.json";
export declare const GENERATION_ARTIFACTS: readonly string[];
/** @param {string} datasetGeneratedAt @param {Record<string, string>} artifacts @param {Record<string, string>} media */
export declare function generationIdFor(datasetGeneratedAt: string, artifacts: Record<string, string>, media: Record<string, string>): string;
/**
 * Build the last-written receipt for one complete generated snapshot.
 * @param {GenerationReceiptPaths} paths
 * @returns {GenerationReceipt}
 */
export declare function createGenerationReceipt({ distDir, mediaRoot }: GenerationReceiptPaths): GenerationReceipt;
/**
 * Validate both the receipt shape and every byte it commits to. The returned
 * parsed snapshot lets verify-media reuse the same authoritative read.
 * @param {GenerationReceiptPaths} paths
 * @returns {GenerationReceiptValidation}
 */
export declare function validateGenerationReceipt(paths: GenerationReceiptPaths): GenerationReceiptValidation;
/**
 * Validate a committed base while allowing only media outputs the named job
 * can recreate. Masters, all JSON inputs, and every unrelated media byte stay
 * strict, so a repair cannot bless a mixed export.
 */
/** @param {GenerationReceiptPaths} paths @param {GenerationRepair} repair @returns {GenerationReceiptValidation & {repairableMedia: string[]}} */
export declare function validateGenerationReceiptForRepair(paths: GenerationReceiptPaths, repair: GenerationRepair): GenerationReceiptValidation & {
    repairableMedia: string[];
};
